- include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"

- import_tasks: uninstall.yml
  when: php_uninstall

- block:
  - import_tasks: system.yml

  - import_tasks: pool.yml
    when: php_create_pool

  - import_tasks: nginx.yml
    when: nginx_install

  when: not php_uninstall
